# Generated by Django 4.1.7 on 2023-04-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=models.EmailField(max_length=254, unique=True), max_length=200, null=True, unique=True),
        ),
    ]
