# Generated by Django 4.2 on 2023-05-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
