# Generated by Django 4.2 on 2023-04-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
