# Generated by Django 4.2 on 2023-04-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
