# Generated by Django 4.2.2 on 2023-06-19 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='content_owner',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_to',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
