# Generated by Django 4.2.2 on 2023-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_remove_subscriber_subscribed_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribers',
            field=models.ManyToManyField(related_name='my_subscribers', to='subscriber.subscriber'),
        ),
    ]
