# Generated by Django 4.2.2 on 2023-06-28 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='total_time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
    ]
