# Generated by Django 4.2 on 2023-05-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lecture_created_at_lecture_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
    ]
