# Generated by Django 4.2 on 2023-05-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_lecture_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default='61e173b0-dfd5-43b8-8878-eb051c65f6c0', on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='course.course'),
            preserve_default=False,
        ),
    ]
