# Generated by Django 4.2.2 on 2023-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_for',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type_of_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
