# Generated by Django 4.2.2 on 2023-06-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_remove_blog_subscribers'),
        ('notification', '0002_rename_body_notification_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(default='86181129-047e-4211-a583-7cd9b4871a1c', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='created_for',
            field=models.ForeignKey(default='86181129-047e-4211-a583-7cd9b4871a1c', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('blog_like', 'Blog Like'), ('blog_comment', 'Blog Comment'), ('new_blog', 'New Blog'), ('subscribe', 'Subscribe'), ('unsubscribe', 'Unsubscribe')], default='post_like', max_length=20),
            preserve_default=False,
        ),
    ]
