# Generated by Django 4.2.2 on 2023-06-22 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(related_name='my_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
