# Generated by Django 4.2 on 2023-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, to='blog.like'),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
