# Generated by Django 4.1.7 on 2023-02-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_published_date_blog_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
