# Generated by Django 4.2 on 2023-06-03 21:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_blog_content_alter_blog_description_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='blog_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
