# Generated by Django 4.1.7 on 2023-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_duration_remove_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='photographer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
