from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import NotificationViewSet

# Create a router and register the NotificationViewSet
router = DefaultRouter()
router.register(r'notifications', NotificationViewSet, basename='notification')

# Define the URL patterns
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]
