# Generated by Django 4.2 on 2023-05-15 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lecture_course'),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='class_type',
            field=models.CharField(default='online', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(default='kenya', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
