name: CI Django & Postgres Tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

  push:
    branches: [ "main" ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: djtesting
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: False
          SECRET_KEY: CI_CD_TEST_KEY
          ALLOWED_HOSTS: ALLOWED_HOSTS
          DATABASE_USER: DATABASE_USER
          DATABASE_PASSWORD: DATABASE_PASSWORD
          DATABASE_DB: DATABASE_DB
          DB_PASSWORD: DB_PASSWORD
          DATABASE_PORT: DATABASE_PORT
          DATABASE_HOST: DATABASE_HOST
          cloud_name : cloud_name
          api_secret : api_secret
          api_key: api_key
          EMAIL_HOST: EMAIL_HOST
          EMAIL_HOST_USER: EMAIL_HOST_USER
          EMAIL_HOST_PASSWORD: EMAIL_HOST_PASSWORD  
          EMAIL_PORT: EMAIL_PORT  
          GITHUB_CLIENT_ID: GITHUB_CLIENT_ID
          GITHUB_SECRET: GITHUB_SECRET
          SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
          SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET    
          SOCIAL_AUTH_FACEBOOK_KEY: SOCIAL_AUTH_FACEBOOK_KEY  
          SOCIAL_AUTH_FACEBOOK_SECRET: SOCIAL_AUTH_FACEBOOK_SECRET
          CELERY_BROKER_URL: CELERY_BROKER_URL
          CELERY_RESULT_BACKEND: CELERY_RESULT_BACKEND
          
        run: |
          python manage.py migrate
          python manage.py test
